name: Build Executable

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution With Force Optimizations
      run: msbuild tim_apple.sln /p:Configuration=Release /p:Platform=x64 /p:Optimize=true /p:LinkIncremental=false

    - name: Upload New Build
      uses: actions/upload-artifact@v4
      with:
        name: tim_apple-v2
        path: "**/Release/tim_apple.exe"
